services:
  mysql:
    image: mysql:8.0
    container_name: gorae-notification-db
    restart: always
    ports:
      - "13308:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: gorae-notification-db
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234